services:
  db:
    image: hub.leniwiec.io/docker_hub/server:2022-latest
    container_name: database
    hostname: db
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD="Q@wertyuiop"
      - MSSQL_PID="Developer"
    networks:
      - simp_cunt_db
    volumes:
      - ./db:/var/opt/mssql

  api:
    image: hub.leniwiec.io/ajp/simp_cunt/api:latest
    container_name: api
    hostname: api
    restart: unless-stopped
    networks:
      - simp_cunt_db
      - simp_cunt_web
    environment:
      - uwu=true
    depends_on:
      - db

  web:
    image: hub.leniwiec.io/ajp/simp_cunt/web:latest
    container_name: web_ui
    hostname: web_ui
    restart: unless-stopped
    environment:
      - Alsdoakdsdasdaosd=asdadoasjkdoa
    networks:
      - simp_cunt_db
      - simp_cunt_web
    depends_on:
      - db
      - api

networks:
  simp_cunt_db:
    name: simp_cunt_db
  simp_cunt_web:
    name: simp_cunt_web
