services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    hostname: db
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD="Q@wertyuiop"
    networks:
      - db
    volumes:
      - ./db:/var/opt/mssql

  api:
    image: my_repo/api
    build:
      context: .
      dockerfile: DockerLoadBalancing.UI.API/Dockerfile
    container_name: api
    hostname: api
    restart: unless-stopped
    networks:
      - db
      - web
    environment:
      - test=true
    depends_on:
      - db

  web:
    image: my_repo/web
    build:
      context: .
      dockerfile: DockerLoadBalancing.UI.Blazor/Dockerfile
    container_name: web_ui
    hostname: web_ui
    restart: unless-stopped
    environment:
      - APILink=http://api:8080/api/People
    networks:
      - simp_cunt_db
      - simp_cunt_web
    depends_on:
      - db
      - api

  nginx_proxy_manager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - web

networks:
  db:
    name: db
  web:
    name: web
